### ISSUE TITLE
Pluto (pet branch) and Red-Black Gauss-Seidel stencil

### ISSUE THREAD

**Issue by kronast** [bondhugula/pluto#11]
I tried to perform some experiments with Pluto (branch pet) and a Red-Black 
Gauss-Seidel stencil, but the resulting code is invalid.

For the input code:

```
#pragma scop
  for (t = 0; t < T; t++) {
      for (i = 1; i < N+1; i++)
          for (j = 1; j < N+1; j++)
              for (k = 1; k < N+1; k++)
                if ((i+j+k)%2 == 0)
                  A[i][j][k] = 0.2 * A[i][j][k]
                      + 0.16 * R[i][j][k]
                      + 0.13 * (A[i - 1][j][k] + A[i][j - 1][k] + A[i][j][k - 1] +
                              A[i + 1][j][k] + A[i][j + 1][k] + A[i][j][k + 1]);

      for (i = 1; i < N+1; i++)
          for (j = 1; j < N+1; j++)
              for (k = 1; k < N+1; k++)
                if ((i+j+k)%2 == 1)
                  A[i][j][k] = 0.2 * A[i][j][k]
                      + 0.16 * R[i][j][k]
                      + 0.13 * (A[i - 1][j][k] + A[i][j - 1][k] + A[i][j][k - 1] +
                              A[i + 1][j][k] + A[i][j + 1][k] + A[i][j][k + 1]);
  }
#pragma endscop
```

Pluto generates (using the call "polycc kernel.c  --pet -o test.c") the 
following code, which does not take the conditions into account:

```
for (t2=0;t2<=3;t2++) {
  for (t4=1;t4<=128;t4++) {
    for (t5=1;t5<=128;t5++) {
      lbv=1;
      ubv=128;
#pragma ivdep
#pragma vector always
      for (t6=lbv;t6<=ubv;t6++) {
        A[ t4][ t5][ t6] = (((0.2 * A[ t4][ t5][ t6]) + (0.16 * R[ t4][ t5][ 
t6])) + (0.13 * (((((A[ t4 - 1][ t5][ t6] + A[ t4][ t5 - 1][ t6]) + A[ t4][ 
t5][ t6 - 1]) + A[ t4 + 1][ t5][ t6]) + A[ t4][ t5 + 1][ t6]) + A[ t4][ t5][ 
t6 + 1])));;
      }
    }
  }
  for (t4=1;t4<=128;t4++) {
    for (t5=1;t5<=128;t5++) {
      lbv=1;
      ubv=128;
#pragma ivdep
#pragma vector always
      for (t6=lbv;t6<=ubv;t6++) {
        A[ t4][ t5][ t6] = (((0.2 * A[ t4][ t5][ t6]) + (0.16 * R[ t4][ t5][ 
t6])) + (0.13 * (((((A[ t4 - 1][ t5][ t6] + A[ t4][ t5 - 1][ t6]) + A[ t4][ 
t5][ t6 - 1]) + A[ t4 + 1][ t5][ t6]) + A[ t4][ t5 + 1][ t6]) + A[ t4][ t5][ 
t6 + 1])));;
      }
    }
  }
}
```

The full example can be found here: https://pastebin.com/yi9SLCqD

**Comment by bondhugula** [comment]
Thank you for reporting this. Although the pet frontend can extract statements in the presence of conditionals that involve modulo w.r.t the constant, the  representation in Pluto doesn't support such constraints that involve modulo w.r.t constant. Pluto should have at least reported the lack of support here.  However, you can get your code working with the following workaround:  fold the conditional into the statement body in one of the following ways:

1. Replace statement body with a call to

           f(&A[i][j][k], A[i][j][k], R[i][j][k], A[i-1][j][k], A[i][j-1][k], ..., A[i][j][k+1], i, j, k);

static inline void f(double *x, double ..., ..., int i, int j, int k) 
{
           if ((i+j+k)%2 == 0) 
                  x = 0.2 * a1  + 0.16 * ...; 
}

2. A simpler alternative is to just use

#define f(x1, x2, ...) (((i+j+k)%2 == 0)? 0.2*x1 + 0.16*... : A[i][j][k])

A[i][j][k] = f(A[i-1][j][k], A[i][j-1][k], ...);

and not use --pet (since using --pet will expand the macro and we end up with the original issue).

On the flip side, this option introduces a write to A[i][j][k] even if there is no update to it.

**Comment by kronast** [comment]
OK, thank you for the quick reply!
I will take a look at it.
