### ISSUE TITLE
Bug Report: Dependence Analysis with PET

### ISSUE THREAD

**Issue by whbldhwj** [bondhugula/pluto#60]
The current Pluto using PET as the parser will fail to extract access functions during the dependence analysis for code such as below:
```
S1: C[i][j] = 0;
S2: C[i][j] += A[i][k] * B[k][j]
```
The RAW dependence between S1 and S2 is associated with both source access function and destination access function as NULL, which is supposed to be set as C[i][j].

The reason is that when setting access functions for each dependence, the current Pluto uses the if condition
```
program.cpp: 
line 422-423
if (options->isldepaccesswise &&
(stmts[dep->src]->reads != NULL && stmts[dep->dest]->reads != NULL)) 
```
When using Clan as the parser, for S1, when the nreads = 0, it will still malloc 0 bytes and assign stmt->reads a unique pointer.
```
osl_pluto.c:
line 833
stmt->reads = (PlutoAccess **)malloc(stmt->nreads * sizeof(PlutoAccess *));
```
However, when using PET, currently, stmt->reads will be set as NULL 
```
program.cpp
line 555-561
if (stmt->nreads > 0) {
  stmt->reads = (PlutoAccess **)malloc(stmt->nreads * sizeof(PlutoAccess *));
}
```
Therefore, it will make the dependence analysis skip the access function assignment when using PET as the parser for such dependence.

**Comment by bondhugula** [comment]
When Pet is used as the frontend, the dependence analysis happens directly on the read and write access relations obtained from pet, i.e., the dependence analysis doesn't happen on stmt->reads/writes. So, I wouldn't expect you to be missing any dependences when using --pet. The code at line 422-423 is only on extracting access information from the computed dependence, and as you point out, won't extract that info (src_acc, dest_acc will be set to NULL). The dependence will still be there, and so you won't have an invalid transformation. To confirm, please see output with:

--moredebug 

(The dependences are printed out.)

Thank you for reporting this though - the guard needs to be fixed so that src/dest acc info is correctly propagated. The 0 byte malloc should be fixed as well.

**Comment by bondhugula** [comment]
@whbldhwj Fixed in these two commits.

**Comment by whbldhwj** [comment]
Yeah I thought it won't affect the transformation. Just I was trying to use the access information and found the field is NULL for such cases. Thanks for the fast response!
